[package]
name = "birthday-team-telegram-bot"
version = "0.1.0"
authors = ["Ricardo M Augusto <ricardo.marques@oruspay.com.br>"]
edition = "2018"

[dependencies]
iron = "*"

[target.heroku]
version = "nightly"